### ISSUE TITLE
How to get the GUI to run?

### ISSUE THREAD

**Issue by donnyv** [bugra9/gdal3.js#34]
I'm new to Vue, so I'm not sure how to get the GUI to run. I'm assuming this is the GUI.
https://github.com/bugra9/gdal3.js/tree/master/apps/app-gui

I tried double clicking the public/index.html but nothing happens. Doesn't have any script tags in it.

**Comment by bugra9** [comment]
Hi @donnyv, sorry for replying so late.


> I'm new to Vue, so I'm not sure how to get the GUI to run. I'm assuming this is the GUI.

Node.js, NPM or yarn app must be installed. In this folder you must run,
- yarn install (or npm install)
- yarn serve (or npm run serve)

And open the link that appears on the cli screen.

> I tried double clicking the public/index.html but nothing happens.

The site won't open with a double click because it takes some files from the local system and browsers do not allow accessing the file system. In a few days I will make a sample app to fetch from cdn and it will open with a double click.

**Comment by bugra9** [comment]
@donnyv, i added single file example running without server required. https://github.com/bugra9/gdal3.js/blob/master/apps/example-singlefile/index.html

**Comment by donnyv** [comment]
Awesome, thanks!
