### ISSUE TITLE
getInfo should handle multiple filesets (eg. rasters in gpkg)

### ISSUE THREAD

**Issue by disarticulate** [bugra9/gdal3.js#61]
getInfo only returns a vector listing or a single raster in a gpkg file.

It looks like for vectors in gpkg it lists the layers, but if you have a gpkg with multiple rasters (or a rasters & vectors table), it only lists the vectors, or a single raster if there's no vectors

gpkg, among others, could have multiple layers. Looks like the logic:
```if (bandCount > 0 && layerCount === 0) { // Raster ``` needs to take into account multiple raster layers @ https://github.com/bugra9/gdal3.js/blob/master/src/allJsFunctions/function/getInfo.js

Lastly, wouldn't it be more consistent with GDAL to implement gdalinfo/ogrinfo to do this function? It looks like they both output json  and you've already got a `ogr2ogr` function working.

(raster/gdalinfo)[https://gdal.org/programs/gdalinfo.html]
(vector/ogrinfo)[https://gdal.org/programs/ogrinfo.html]

**Comment by bugra9** [comment]
Hi @disarticulate,

I implemented gdalinfo and ogrinfo applications in the latest version (2.6.0).
https://gdal3.js.org/docs/module-a_gdalinfo.html
https://gdal3.js.org/docs/module-a_ogrinfo.html

After opening the file, you can access this output with the info attribute in the dataset object.
https://gdal3.js.org/docs/TypeDefs.html

I don't know how to differentiate between raster and vector. I don't see a workable method on the Gdal side. Therefore, I added width and height checks instead of layer count checks. I hope it is true :)
https://github.com/bugra9/gdal3.js/blob/master/src/allJsFunctions/function/open.js#L119

**Comment by disarticulate** [comment]
thanks. I'll check it out when I get to it again.
